// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
abstract class ECoreInitErrors_t {
  static const int ECIERR_OK = 0;
  static const int ECIERR_INTERNAL = 1;
  static const int ECIERR_INVALID_INST = 2;
  static const int ECIERR_ALREADY_INIT = 3;
  static const int ECIERR_NOT_INIT = 4;
  static const int ECIERR_ALREADY_STARTED = 5;
  static const int ECIERR_OSAL = 6;
  static const int ECIERR_INVALID_CMD_LINE = 7;
  static const int ECIERR_INVALID_USER_ID = 8;
  static const int ECIERR_INVALID_USER_PASSWORD = 9;
  static const int ECIERR_INVALID_VOCODER = 10;
  static const int ECIERR_INVALID_SERVER_ADDRESS = 11;
  static const int ECIERR_INVALID_RECORD_LENGTH = 12;
  static const int ECIERR_NUM_ERRORS = 13;
  static const int ECIERR_MAX_VAL = 2147483647;
}

const String STR_OK = 'OK';

const String STR_FAILED = 'failed';

const String STR_UNSUPPORTED = 'unsupported';

const String STR_LENGTH_EXCEEDED = 'length-exceeded';

const String STR_VERSION = 'version';

const String STR_IPRS_PROTOCOL = 'protocol-version';

const String STR_GET_IPRS_PROTOCOL = 'get-protocol-version';

const String STR_CLIENT_OWN_ID = 'client-own-id';

const String STR_CLIENT_OWN_NAME = 'client-own-name';

const String STR_SERVICES = 'services';

const String STR_DISPATCHER = 'dispatcher';

const String STR_ENABLED_SERVICES = 'enabled-services';

const String STR_FINISHED = 'finished';

const String STR_SIGN_IN_FAILED = 'sign-in-failed';

const String STR_NO_USER_ID = 'no-user-id';

const String STR_NO_PASSWORD = 'no-password';

const String STR_NO_SERVER = 'no-server';

const String STR_INTERNAL_ERROR = 'internal-error';

const String STR_INVALID_INSTANCE = 'invalid-instance';

const String STR_ALREADY_INITIALIZED = 'already-initialized';

const String STR_NOT_INITIALIZED = 'not-initialized';

const String STR_ALREADY_STARTED = 'already-started';

const String STR_OSAL = 'OSAL';

const String STR_INVALID_COMMAND_LINE = 'invalid-command-line';

const String STR_NO_VOCODER = 'no-vocoder';

const String STR_INVALID_RECORD_LENGTH = 'invalid-record-length';

const String STR_SET = 'set';

const String STR_USERNAME = 'username';

const String STR_PASSWORD = 'password';

const String STR_SERVER = 'server';

const String STR_LOGIN_LEVEL = 'login-level';

const String STR_INITIAL_STATE = 'initial-state';

const String STR_AUDIO_RECORD_LENGTH = 'audio-recording-length';

const String STR_NAT_INTERVAL = 'nat-interval';

const String STR_CONTROL_PORT = 'control-port';

const String STR_AUDIO_PORT = 'audio-port';

const String STR_DEFAULT = 'default';

const String STR_CONN_MGR_USE = 'conn-mgr';

const String STR_FORGET_ME = 'forget-me';

const String STR_REMEMBER_USERNAME = 'remember-username';

const String STR_REMEMBER_PASSWORD = 'remember-password';

const String STR_AUTOMATIC = 'automatic';

const String STR_WAVE_INPUT_DEVICE = 'wave-input-device';

const String STR_WAVE_OUTPUT_DEVICE = 'wave-output-device';

const String STR_AUDIO_INPUT_RATE = 'audio-input-rate';

const String STR_AUDIO_OUTPUT_RATE = 'audio-output-rate';

const String STR_SIGN_IN = 'sign-in';

const String STR_SIGN_OUT = 'sign-out';

const String STR_CHANGE_STATE = 'change-state';

const String STR_STATE = 'state';

const String STR_OFFLINE = 'offline';

const String STR_DISCONNECTING = 'disconnecting';

const String STR_SHUTTING_DOWN = 'shutting-down';

const String STR_ACQUIRING_NETWORK = 'acquiring-network';

const String STR_CONNECTING = 'connecting';

const String STR_SYNCHRONIZING = 'synchronizing';

const String STR_ONLINE = 'online';

const String STR_PAGEME = 'page-me';

const String STR_DND = 'DND';

const String STR_NO_NETWORK = 'no-network';

const String STR_NO_SERVICE = 'no-service';

const String STR_QUIT = 'quit';

const String STR_TERMINATE = 'terminate';

const String STR_SIGN_IN_DENIED = 'sign-in denied';

const String STR_UNKNOWN = 'unknown';

const String STR_UNRECOGNIZED = 'unrecognized';

const String STR_AUTH_ERROR = 'auth-error';

const String STR_WRONG_VERSION = 'wrong-version';

const String STR_UNKNOWN_NETWORK = 'unknown-network';

const String STR_INVALID_PARAMETERS = 'invalid-parameters';

const String STR_CREDIT_ERROR = 'credit-error';

const String STR_SERVER_ERROR = 'server-error';

const String STR_NAT_ADDRESS_ERROR = 'NAT-address-error';

const String STR_CALL = 'call';

const String STR_ORIGINATING = 'originating';

const String STR_CONNECTED = 'connected';

const String STR_ACCEPTED = 'accepted';

const String STR_MODIFIED = 'modified';

const String STR_QUERY = 'query';

const String STR_CANCELED = 'canceled';

const String STR_REQUESTED = 'requested';

const String STR_ENDED = 'ended';

const String STR_PRIVATE = 'private';

const String STR_CHAT_ROOM = 'chat-room';

const String STR_CONFERENCE = 'conference';

const String STR_PERSONAL_GROUP = 'personal-group';

const String STR_ADHOC = 'ad-hoc';

const String STR_CALL_PRESENCE = 'call-presence';

const String STR_CALL_INFO = 'call-info';

const String STR_SESSION_MEMBERS = 'call-participants';

const String STR_CALL_REQUEST = 'call-request';

const String STR_LEAVE = 'leave';

const String STR_INCOMING_CALL = 'incoming-call';

const String STR_REJECTED = 'rejected';

const String STR_TIMED_OUT = 'timed-out';

const String STR_REQUEST = 'request';

const String STR_PARTICIPANT = 'participant';

const String STR_ADD_TO_SESSION = 'add-to-session';

const String STR_PRIORITY = 'priority';

const String STR_LOW = 'low';

const String STR_NORMAL = 'normal';

const String STR_HIGH = 'high';

const String STR_URGENT = 'urgent';

const String STR_EMERGENCY = 'emergency';

const String STR_ANNOUNCEMENT = 'announcement';

const String STR_DRIVER = 'driver';

const String STR_PASSENGERS = 'passengers';

const String STR_OUTSIDE_SPEAKER = 'outside-speaker';

const String STR_INITIATOR_ENDS_CALL = 'initiator-ends-call';

const String STR_SIMPLEX = 'simplex';

const String STR_NON_INITIATOR_CANNOT_LEAVE = 'non-initiator-cannot-leave';

const String STR_INITIATOR = 'initiator';

const String STR_ALL = 'all';

const String STR_AUDIO_OUTPUT_DEVICE = 'audio-output-device';

const String STR_ORIGINATION_ABORTED = 'origination-aborted';

const String STR_INVALID_NUMBER = 'invalid-number';

const String STR_OWN_NUMBER = 'own-number';

const String STR_NO_DEFAULT_CHATROOM = 'no-default-chatroom';

const String STR_NO_PERMISSION = 'no-permission';

const String STR_NO_CREDIT = 'no-credit';

const String STR_USER_UNAVAILABLE = 'user-unavailable';

const String STR_SERVER_CONFIGURATION = 'server-configuration';

const String STR_NORMALLY = 'normally';

const String STR_IDLE_TIMEOUT = 'idle-timeout';

const String STR_INTERRUPTED_BY_OUTGOING_CALL = 'interrupted-by-outgoing-call';

const String STR_INTERRUPTED_BY_INCOMING_CALL = 'interrupted-by-incoming-call';

const String STR_INTERRUPTED_BY_INCOMING_VOICE_CALL =
    'interrupted-by-incoming-voice-call';

const String STR_GROUP_UNAVAILABLE = 'group-unavailable';

const String STR_TERMINATED_NO_PERMISSION = 'terminated-no-permission';

const String STR_TERMINATED_NO_CREDIT = 'terminated-no-credit';

const String STR_TERMINATED_BY_SERVER = 'terminated-by-server';

const String STR_PEER_SWITCHED_CALL = 'peer-switched-call';

const String STR_PEER_LOGGED_OUT = 'peer-logged-out';

const String STR_GET_CONTACT_LIST = 'get-contact-list';

const String STR_GET_GROUP_LIST = 'get-group-list';

const String STR_GET_GROUP_MEMBERS = 'get-group-members';

const String STR_CONTACT_RECORD = 'contact-record';

const String STR_GROUP_RECORD = 'group-record';

const String STR_NAME = 'name';

const String STR_CONTACT = 'contact';

const String STR_CONTACT_LIST = 'contact-list';

const String STR_CURRENT_CALL = 'current-call';

const String STR_GROUP = 'group';

const String STR_GROUP_NOTIFICATIONS = 'group-notifications';

const String STR_ON = 'on';

const String STR_OFF = 'off';

const String STR_CONTACT_UPDATE = 'contact-update';

const String STR_ADDED_TO = 'added-to';

const String STR_REMOVED_FROM = 'removed-from';

const String STR_IN_CALL = 'in-call';

const String STR_CONTACT_SEARCH = 'contact-search';

const String STR_ID = 'id';

const String STR_CONTACT_SEARCH_RES = 'result';

const String STR_CONTACT_ADD = 'contact-add';

const String STR_CONTACT_DELETE = 'contact-remove';

const String STR_TALKER = 'talker';

const String STR_YOU = 'you';

const String STR_NONE = 'none';

const String STR_PTT = 'PTT';

const String STR_END = 'END';

const String STR_ENABLED = 'enabled';

const String STR_DISABLED = 'disabled';

const String STR_UP = 'up';

const String STR_DOWN = 'down';

const String STR_REMOTE_RECORD = 'remote-record';

const String STR_START = 'start';

const String STR_STOP = 'stop';

const String STR_SILENT = 'silent';

const String STR_AUDIO_FILE = 'audio-file';

const String STR_RECORD = 'record';

const String STR_STOP_RECORD = 'stop-record';

const String STR_TRANSMIT = 'transmit';

const String STR_STOP_TRANSMIT = 'stop-transmit';

const String STR_SOS = 'sos';

const String STR_SOS_HANDLER = 'sos-handler';

const String STR_RECEIVED = 'received';

const String STR_APPROVE = 'approve';

const String STR_CLEAR = 'clear';

const String STR_APPROVED = 'approved';

const String STR_CLEARED = 'cleared';

const String STR_SEND = 'send';

const String STR_ACKED = 'acked';

const String TEXT_CHAT = 'text-chat';

const String IM_CREATE = 'create';

const String IM_LIST = 'list';

const String IM_SEND = 'send';

const String IM_REMOVE = 'remove';

const String IM_MESSAGE_ADDED = 'message added';

const String IM_INCOMING = 'incoming';

const String IM_OUTGOING = 'outgoing';

const String IM_DIALOG = 'dialog';

const String IM_ADDED = 'added';

const String IM_REMOVED = 'removed';

const String STR_POSITION = 'position';

const String STR_UPDATE = 'update';

const int CHR_POSITION_SEPARATOR = 61;

const String STR_RETRIEVE = 'retrieve';

const String STR_TRACK = 'track';

const String STR_DURATION = 'duration';

const String STR_STOP_TRACKING = 'stop-tracking';

const String STR_BT = 'bluetooth';

const String STR_INIT = 'init';

const String STR_ENABLE = 'enable';

const String STR_DISABLE = 'disable';

const String STR_VIGILITE = 'vigilite';

const String STR_BT_BUTTON = 'ptt_button';

const String STR_BT_AUDIO = 'audio';

const String STR_MD5_AUTH = 'MD5-auth';

const String STR_MD5_RESPONSE = 'MD5-response';

const String STR_ERROR = 'error';

const String STR_GENERAL = 'general';

const String STR_BAD_DEFAULT_GROUP = 'bad-default-group';

const String STR_CONTACT_OFFLINE = 'contact-offline';

const String STR_BAD_PTT = 'bad-PTT';

const String STR_CANNOT_ADD_CONTACT = 'cannot-add-contact';

const String STR_CANNOT_EDIT_CONTACT = 'cannot-edit-contact';

const String STR_CANNOT_REMOVE_CONTACT = 'cannot-remove-contact';

const String STR_CONTACT_NOT_FOUND = 'contact-not-found';

const String STR_CANNOT_ADD_OWN_ID = 'cannot-add-own-ID';

const String STR_CONTACT_ALREADY_EXIST = 'contact-already-exist';

const String STR_CANNOT_ADD_GROUP = 'cannot-add-group';

const String STR_CANNOT_EDIT_GROUP = 'cannot-edit-group';

const String STR_CANNOT_REMOVE_GROUP = 'cannot-remove-group';

const String STR_GROUP_ALREADY_EXIST = 'group-already-exist';

const String STR_INVALID_ID = 'invalid-ID';

const String STR_INVALID_CHARACTERS = 'invalid-characters';

const String STR_NO_SESSION = 'no-session';

const String STR_NOT_SUPPORTED = 'not-supported';

const String STR_CONTACT_UNAVAILABLE = 'contact-unavailable';

const String STR_CANNOT_SEND_TEXT_MESSAGE = 'cannot-send-text-message';

const String STR_NOT_SUPPORTED_BY_RECIPIENTS = 'not-supported-by-recipients';

const String STR_LOGGED_OUT_LOGGED_IN_ELSEWHERE =
    'logged-out-logged-in-elsewhere';

const String STR_LOGGED_OUT_SUSPENDED_OR_DELETED =
    'logged-out-suspended-or-deleted';

const String STR_LOGGED_OUT_NO_CREDIT = 'logged-out-no-credit';

const String STR_CANNOT_BIND_SOCKET = 'cannot-bind-socket';
